// Code generated by goctl. DO NOT EDIT.
// Source: dependency.proto

package dependencyservice

import (
	"context"

	"mathless-backend/app/dependency/cmd/rpc/dependency"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DownloadDependencyRequest  = dependency.DownloadDependencyRequest
	DownloadDependencyResponse = dependency.DownloadDependencyResponse
	GetDependencyRequest       = dependency.GetDependencyRequest
	GetDependencyResponse      = dependency.GetDependencyResponse
	SearchDependenciesRequest  = dependency.SearchDependenciesRequest
	SearchDependenciesResponse = dependency.SearchDependenciesResponse

	DependencyService interface {
		// 获取依赖内容
		GetDependency(ctx context.Context, in *GetDependencyRequest, opts ...grpc.CallOption) (*GetDependencyResponse, error)
		// 下载依赖
		DownloadDependency(ctx context.Context, in *DownloadDependencyRequest, opts ...grpc.CallOption) (*DownloadDependencyResponse, error)
		// 搜索依赖
		SearchDependencies(ctx context.Context, in *SearchDependenciesRequest, opts ...grpc.CallOption) (*SearchDependenciesResponse, error)
	}

	defaultDependencyService struct {
		cli zrpc.Client
	}
)

func NewDependencyService(cli zrpc.Client) DependencyService {
	return &defaultDependencyService{
		cli: cli,
	}
}

// 获取依赖内容
func (m *defaultDependencyService) GetDependency(ctx context.Context, in *GetDependencyRequest, opts ...grpc.CallOption) (*GetDependencyResponse, error) {
	client := dependency.NewDependencyServiceClient(m.cli.Conn())
	return client.GetDependency(ctx, in, opts...)
}

// 下载依赖
func (m *defaultDependencyService) DownloadDependency(ctx context.Context, in *DownloadDependencyRequest, opts ...grpc.CallOption) (*DownloadDependencyResponse, error) {
	client := dependency.NewDependencyServiceClient(m.cli.Conn())
	return client.DownloadDependency(ctx, in, opts...)
}

// 搜索依赖
func (m *defaultDependencyService) SearchDependencies(ctx context.Context, in *SearchDependenciesRequest, opts ...grpc.CallOption) (*SearchDependenciesResponse, error) {
	client := dependency.NewDependencyServiceClient(m.cli.Conn())
	return client.SearchDependencies(ctx, in, opts...)
}
