// Code generated by goctl. DO NOT EDIT.
package handler

import (
	user2 "mathless-backend/app/user/cmd/api/internal/handler/user"
	"mathless-backend/app/user/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user2.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user2.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/verifyEmail",
				Handler: user2.VerifyEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)
}
