// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	dependency "mathless-backend/app/dependency/cmd/api/internal/handler/dependency"
	"mathless-backend/app/dependency/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: dependency.SearchDependenciesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: dependency.GetDependenciesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/download",
				Handler: dependency.DownloadDependencyHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/dependency"),
	)
}
