// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: dependency.proto

package dependency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDependency
type GetDependencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DependencyFileLocation string `protobuf:"bytes,1,opt,name=DependencyFileLocation,proto3" json:"DependencyFileLocation,omitempty"`
}

func (x *GetDependencyRequest) Reset() {
	*x = GetDependencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dependency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyRequest) ProtoMessage() {}

func (x *GetDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyRequest.ProtoReflect.Descriptor instead.
func (*GetDependencyRequest) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{0}
}

func (x *GetDependencyRequest) GetDependencyFileLocation() string {
	if x != nil {
		return x.DependencyFileLocation
	}
	return ""
}

type GetDependencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackagesJson string `protobuf:"bytes,1,opt,name=PackagesJson,proto3" json:"PackagesJson,omitempty"`
}

func (x *GetDependencyResponse) Reset() {
	*x = GetDependencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dependency_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDependencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyResponse) ProtoMessage() {}

func (x *GetDependencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyResponse.ProtoReflect.Descriptor instead.
func (*GetDependencyResponse) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{1}
}

func (x *GetDependencyResponse) GetPackagesJson() string {
	if x != nil {
		return x.PackagesJson
	}
	return ""
}

// DownloadDependency
type DownloadDependencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileLocation string `protobuf:"bytes,1,opt,name=FileLocation,proto3" json:"FileLocation,omitempty"`
	Requirements string `protobuf:"bytes,2,opt,name=Requirements,proto3" json:"Requirements,omitempty"`
}

func (x *DownloadDependencyRequest) Reset() {
	*x = DownloadDependencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dependency_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDependencyRequest) ProtoMessage() {}

func (x *DownloadDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDependencyRequest.ProtoReflect.Descriptor instead.
func (*DownloadDependencyRequest) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadDependencyRequest) GetFileLocation() string {
	if x != nil {
		return x.FileLocation
	}
	return ""
}

func (x *DownloadDependencyRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

type DownloadDependencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownloadDependencyResponse) Reset() {
	*x = DownloadDependencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dependency_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadDependencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDependencyResponse) ProtoMessage() {}

func (x *DownloadDependencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDependencyResponse.ProtoReflect.Descriptor instead.
func (*DownloadDependencyResponse) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{3}
}

// SearchDependencies
type SearchDependenciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *SearchDependenciesRequest) Reset() {
	*x = SearchDependenciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dependency_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDependenciesRequest) ProtoMessage() {}

func (x *SearchDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDependenciesRequest.ProtoReflect.Descriptor instead.
func (*SearchDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{4}
}

func (x *SearchDependenciesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchDependenciesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchDependenciesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchDependenciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packages []string `protobuf:"bytes,1,rep,name=Packages,proto3" json:"Packages,omitempty"`
	Total    int32    `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *SearchDependenciesResponse) Reset() {
	*x = SearchDependenciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dependency_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDependenciesResponse) ProtoMessage() {}

func (x *SearchDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDependenciesResponse.ProtoReflect.Descriptor instead.
func (*SearchDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{5}
}

func (x *SearchDependenciesResponse) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *SearchDependenciesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_dependency_proto protoreflect.FileDescriptor

var file_dependency_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x4e,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x19, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f,
	0x0a, 0x19, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x4e, 0x0a, 0x1a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x32,
	0xb3, 0x02, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x20, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x25, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x63, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dependency_proto_rawDescOnce sync.Once
	file_dependency_proto_rawDescData = file_dependency_proto_rawDesc
)

func file_dependency_proto_rawDescGZIP() []byte {
	file_dependency_proto_rawDescOnce.Do(func() {
		file_dependency_proto_rawDescData = protoimpl.X.CompressGZIP(file_dependency_proto_rawDescData)
	})
	return file_dependency_proto_rawDescData
}

var file_dependency_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dependency_proto_goTypes = []interface{}{
	(*GetDependencyRequest)(nil),       // 0: dependency.GetDependencyRequest
	(*GetDependencyResponse)(nil),      // 1: dependency.GetDependencyResponse
	(*DownloadDependencyRequest)(nil),  // 2: dependency.DownloadDependencyRequest
	(*DownloadDependencyResponse)(nil), // 3: dependency.DownloadDependencyResponse
	(*SearchDependenciesRequest)(nil),  // 4: dependency.SearchDependenciesRequest
	(*SearchDependenciesResponse)(nil), // 5: dependency.SearchDependenciesResponse
}
var file_dependency_proto_depIdxs = []int32{
	0, // 0: dependency.DependencyService.GetDependency:input_type -> dependency.GetDependencyRequest
	2, // 1: dependency.DependencyService.DownloadDependency:input_type -> dependency.DownloadDependencyRequest
	4, // 2: dependency.DependencyService.SearchDependencies:input_type -> dependency.SearchDependenciesRequest
	1, // 3: dependency.DependencyService.GetDependency:output_type -> dependency.GetDependencyResponse
	3, // 4: dependency.DependencyService.DownloadDependency:output_type -> dependency.DownloadDependencyResponse
	5, // 5: dependency.DependencyService.SearchDependencies:output_type -> dependency.SearchDependenciesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dependency_proto_init() }
func file_dependency_proto_init() {
	if File_dependency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dependency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDependencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dependency_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDependencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dependency_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadDependencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dependency_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadDependencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dependency_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDependenciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dependency_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDependenciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dependency_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dependency_proto_goTypes,
		DependencyIndexes: file_dependency_proto_depIdxs,
		MessageInfos:      file_dependency_proto_msgTypes,
	}.Build()
	File_dependency_proto = out.File
	file_dependency_proto_rawDesc = nil
	file_dependency_proto_goTypes = nil
	file_dependency_proto_depIdxs = nil
}
