// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	plugin "mathless-backend/app/plugin/internal/handler/plugin"
	"mathless-backend/app/plugin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/invokeFc",
				Handler: plugin.RunFcHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/plugin"),
	)
}
