// Code generated by goctl. DO NOT EDIT.
package types

type InvokeFcReq struct {
	ServiceName  string `json:"serviceName"`
	FunctionName string `json:"functionName"`
	Data         string `json:"data"`
}

type InvokeFcResp struct {
	Result string `json:"message"`
}
