// Code generated by goctl. DO NOT EDIT.
// Source: dependency.proto

package server

import (
	"context"

	"mathless-backend/app/dependency/cmd/rpc/dependency"
	"mathless-backend/app/dependency/cmd/rpc/internal/logic"
	"mathless-backend/app/dependency/cmd/rpc/internal/svc"
)

type DependencyServiceServer struct {
	svcCtx *svc.ServiceContext
	dependency.UnimplementedDependencyServiceServer
}

func NewDependencyServiceServer(svcCtx *svc.ServiceContext) *DependencyServiceServer {
	return &DependencyServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取依赖内容
func (s *DependencyServiceServer) GetDependency(ctx context.Context, in *dependency.GetDependencyRequest) (*dependency.GetDependencyResponse, error) {
	l := logic.NewGetDependencyLogic(ctx, s.svcCtx)
	return l.GetDependency(in)
}

// 下载依赖
func (s *DependencyServiceServer) DownloadDependency(ctx context.Context, in *dependency.DownloadDependencyRequest) (*dependency.DownloadDependencyResponse, error) {
	l := logic.NewDownloadDependencyLogic(ctx, s.svcCtx)
	return l.DownloadDependency(in)
}

// 搜索依赖
func (s *DependencyServiceServer) SearchDependencies(ctx context.Context, in *dependency.SearchDependenciesRequest) (*dependency.SearchDependenciesResponse, error) {
	l := logic.NewSearchDependenciesLogic(ctx, s.svcCtx)
	return l.SearchDependencies(in)
}
