// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Email      string `json:"email"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	VerifyCode string `json:"verifyCode"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type VerifyEmailReq struct {
	Email string `json:"email"`
}

type VerifyEmailResp struct {
	Code string `json:"code"`
}
